server:
 port: 8083

spring:
 application:
  name: charge
 datasource:
  name: charge
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://localhost:3306/charge
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  # druid配置
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat
  maxPoolPreparedStatementPerConnectionSize: 20
  useGlobalDataSourceStat: true
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
# mybatis
mybatis:
 mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/impl/*.xml
# typeAliasesPackage: com.charge.dao.impl
# pagehelper分页插件
pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql
eureka:
 client:
  service-url:
   defaultZone: http://192.168.7.135:8761/eureka/
logging:
 level:
  com.charge.dao : debug